name: MP-QQ CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-qq-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Node ENV
        uses: actions/setup-node@master
        with:
          node-version: 12.13.0

      - name: Install Dependencies
        run: npm install
        
      - name: PreBuild
        run: npm run build:mp-qq && cd dist/build/mp-qq

      - name: Build
        uses: docker://qqminiapp/build:latest
        env:
          PLUGIN_VERSION: 1.0.0
          PLUGIN_DESC: CI自动构建上传
          PLUGIN_APPTOKEN: ${{ secrets.QQ_UPLOAD_TOKEN }}
          PLUGIN_BUILDUSER: ${{ github.actor }}
          PLUGIN_EXPERIENCE: true

  ding-notice:
    needs: build-qq-ci
    runs-on: ubuntu-latest

    steps:
      - name: Ding-Notice
        if: ${{ success() }}
        uses: fifsky/dingtalk-action@master
        with:
          url: ${{ secrets.DINGTALK_WEBHOOK }}
          type: markdown
          content: |
            # 👨‍💻 [mp-ci]QQ小程序: 构建&发布成功 🎉🎉🎉
            > Build of sword-app success
            > ^_^ from github action message

# 参考
# 1. https://segmentfault.com/a/1190000039125224
