name: MP-WEIXIN CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-weixin-ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build:mp-weixin

      # see Project/Settings/Secrets
      - name: Generate private key for upload
        run: echo "$WEIXIN_UPLOAD_PRIVATE_KEY" > private.key
        env:
          UPLOAD_PRIVATE_KEY: ${{ secrets.WEIXIN_UPLOAD_PRIVATE_KEY }}
      # 上传代码
      - name: Upload to WeChat
        run: npx mp-ci upload ./ --pkp=./private.key

  ding-notice:
    needs: build-weixin-ci
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - name: Ding-Notice
        if: ${{ success() }}
        uses: fifsky/dingtalk-action@master
        with:
          url: ${{ secrets.DINGTALK_WEBHOOK }}
          type: markdown
          content: |
            # 👨‍💻 [mp-ci]微信小程序: 构建&发布成功 🎉🎉🎉
            > Build of [# {{$GITHUB_REPOSITORY}}] success
            > ^_^ from github action message

# 参考
# 1. https://segmentfault.com/a/1190000039125224
